[workspace]
channels = ["conda-forge"]
name = "prefect3 test"
platforms = ["linux-64", "osx-64"]

[dependencies]
prefect = "3.*"
python = "<3.14"
bluesky-tiled-plugins = ">=2"
prefect-docker = "*"
tiled-client = ">=0.2.3"
httpx = ">=0.28.1,<0.29"
pandas = ">=3.0.0,<4"
numpy = ">=2.3.5,<3"
h5py = ">=3.15.1,<4"
pillow = ">=12.1.0,<13"
ipython = ">=9.9.0,<10"
